alias vim='nvim'
alias ytpl='yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" "$1"'
alias zsh='nvim ~/.zshrc'
alias zz='source ~/.zshrc && echo Config reloaded'
alias cool='cmatrix -bsru 8'
alias a='cd && clear'
alias b='cd -'
alias c='clear'
alias d='cd $(find . -type d -name ".git" -prune -o -type d -print | fzf) && ls'
alias cc='cd ~/.config && nvim .'
alias cs='cd ~/.config/shell && nvim .'
alias cn='cd ~/.config/nvim && nvim .'
alias cg='cd ~/.config/ghostty && nvim .'
alias ls='lsd'
alias nv='nvim $(fzf -m --preview="bat --color=always {}")'
alias tt='tmux new-session -d -s dev -c ~ -n nvim ";" new-window -c ~ -n zsh ";" select-window -t nvim'
alias activate='source .venv/bin/activate --active'
alias paint='kitty icat'
alias n='nvim .'
alias ti='selected_dir=$(find ~ -type d 2>/dev/null | fzf --prompt="Select directory: ") && tmux new-session -s $(basename "$selected_dir") -c $selected_dir -n nvim ";" new-window -c $selected_dir -n zsh ";" select-window -t nvim'
alias ta='tmux attach -t $(tmux ls -F "#{session_name}" 2>/dev/null | fzf --prompt="Select session: " --height=10 --reverse)'
alias tk='tmux kill-session -t $(tmux ls -F "#{session_name}" 2>/dev/null | fzf --prompt="Select session: " --height=10 --reverse)'
alias gc='f(){ username=$(echo "$1" | sed -n "s|.*github\.com[/:]\\([^/]*\\)/.*|\\1|p"); repo=$(basename "$1" .git); mkdir -p ~/workspace/github/"$username"; cd ~/workspace/github/"$username"; git clone "$1"; tmux new-session -d -s "$repo" -c "$repo" -n nvim ";" new-window -c "$repo" -n zsh ";" select-window -t nvim;unset -f f;cd -; }; f'
